import { ResearchReport } from "../types";

/**
 * Downloads a structured text/markdown report of the research
 */
export function downloadReportAsMarkdown(report: ResearchReport): void {
  const markdownContent = `
# AI Investment Research Report: ${report.company.name} (${report.company.ticker})
Report Generated: ${new Date(report.timestamp).toLocaleString()}

---

## 1. Executive Recommendation
- **Decision**: ${report.recommendation.decision}
- **Confidence**: ${report.recommendation.confidence}%
- **Overall Score**: ${report.recommendation.scores.overall}/100

### scores:
- Growth Score: ${report.recommendation.scores.growth}/100
- Risk Score: ${report.recommendation.scores.risk}/100 (Higher is safer)
- Valuation Score: ${report.recommendation.scores.valuation}/100
- Financial Score: ${report.recommendation.scores.financial}/100
- Innovation Score: ${report.recommendation.scores.innovation}/100

### Detailed Thesis
${report.recommendation.reasoning}

---

## 2. Company Profile
- **CEO**: ${report.company.ceo}
- **Industry**: ${report.company.industry}
- **Headquarters**: ${report.company.hq}
- **Market Cap**: ${report.company.marketCap}
- **Revenue**: ${report.company.revenue}
- **Employees**: ${report.company.employees}
- **Website**: ${report.company.website}

### Business Description
${report.company.description}

---

## 3. Financial Analysis
- **Revenue Growth (YoY)**: ${report.financials.revenueGrowth}%
- **Profit Growth (YoY)**: ${report.financials.profitGrowth}%
- **Debt-to-Equity**: ${report.financials.debtToEquity}
- **Operating Margin**: ${report.financials.operatingMargin}%
- **Free Cash Flow**: ${report.financials.freeCashFlow}
- **P/E Ratio**: ${report.financials.peRatio}
- **EPS**: ${report.financials.eps}

---

## 4. SWOT Analysis

### Strengths
${report.swot.strengths.map(s => `- ${s}`).join("\n")}

### Weaknesses
${report.swot.weaknesses.map(w => `- ${w}`).join("\n")}

### Opportunities
${report.swot.opportunities.map(o => `- ${o}`).join("\n")}

### Threats
${report.swot.threats.map(t => `- ${t}`).join("\n")}

---

## 5. Risk Assessment
- **Business Risk**: ${report.risk.businessRisk}
- **Market Risk**: ${report.risk.marketRisk}
- **Regulatory Risk**: ${report.risk.regulatoryRisk}
- **Technology Risk**: ${report.risk.technologyRisk}
- **Financial Risk**: ${report.risk.financialRisk}

---

## 6. Competitive Landscape
${report.competitors.map(c => `
### ${c.name} (${c.ticker})
- Market Cap: ${c.marketCap}
- P/E Ratio: ${c.peRatio}
- Revenue: ${c.revenue}
- Operating Margin: ${c.margin}%
`).join("\n")}

---
Generated by InsideIIM Altuni AI Labs. All Rights Reserved.
  `.trim();

  const blob = new Blob([markdownContent], { type: "text/markdown;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute("download", `${report.company.ticker}_Investment_Research_Report.md`);
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Copies the raw markdown report text to clipboard
 */
export async function copyReportToClipboard(report: ResearchReport): Promise<boolean> {
  const content = `
AI Investment Research Report: ${report.company.name} (${report.company.ticker})
Decision: ${report.recommendation.decision} | Confidence: ${report.recommendation.confidence}%
Overall Score: ${report.recommendation.scores.overall}/100

Growth: ${report.recommendation.scores.growth} | Risk: ${report.recommendation.scores.risk} | Valuation: ${report.recommendation.scores.valuation} | Financial: ${report.recommendation.scores.financial} | Innovation: ${report.recommendation.scores.innovation}

Investment Thesis:
${report.recommendation.reasoning.replace(/#/g, "")}

Company Profile:
CEO: ${report.company.ceo} | Industry: ${report.company.industry} | HQ: ${report.company.hq}
Market Cap: ${report.company.marketCap} | Revenue: ${report.company.revenue}

Financials:
Growth (Rev/Profit): ${report.financials.revenueGrowth}% / ${report.financials.profitGrowth}%
Operating Margin: ${report.financials.operatingMargin}% | PE: ${report.financials.peRatio} | EPS: ${report.financials.eps}
  `.trim();

  try {
    await navigator.clipboard.writeText(content);
    return true;
  } catch (err) {
    console.error("Failed to copy report:", err);
    return false;
  }
}

/**
 * Triggers browser print, which defaults to saving as PDF if user selects PDF print option
 */
export function exportReportToPDF(): void {
  if (typeof window !== "undefined") {
    window.print();
  }
}
